trigger:
- master
- features/*
- fixes/*
- improvements/*

pool:
  vmImage: 'ubuntu-18.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '11.x'
  displayName: 'Install Node.js'
- script: |
    npm install
  displayName: 'npm install'
- script: |
    gulp
  displayName: 'gulp'
