trigger:
- master
- features/*
- fixes/*
- improvements/*

pool:
  vmImage: 'ubuntu-18.04'

variables:
  releaseConfig: 'release'
  debugConfig: 'debug'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '11.x'
  displayName: 'Install Node.js'
- script: |
    npm install
  displayName: 'npm install'
- script: |
    gulp
  displayName: 'gulp'
- script: |
    WEB_LIBRARY_VERSION=$(grep -o '<version>.*</version>' version|sed 's/\(<version>\|<\/version>\)//g')
    echo "##vso[task.setvariable variable=webLibraryVersion]$WEB_LIBRARY_VERSION"
  failOnStderr: true
- task: Docker@2
  displayName: 'Build & Push an image (debug)'
  inputs:
    containerRegistry: ghmonitor019de6.azurecr.io
    repository: portal
    Dockerfile: Dockerfile
    tags: |
      $(webLibraryVersion)-$(debugConfig)
      latest-$(debugConfig)
  condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'))
- task: Docker@2
  displayName: 'Build & Push an image (release)'
  inputs:
    containerRegistry: ghmonitor019de6.azurecr.io
    repository: portal
    Dockerfile: Dockerfile
    tags: |
      latest
      latest-$(releaseConfig)
      $(webLibraryVersion)-$(releaseConfig)
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
- script: |
    sed 's/@version/$(webLibraryVersion)/g' k8s-deployment-manifest.yml.tmplt > k8s-deployment-manifest.yml
  displayName: 'bake manifest'
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: 'k8s-deployment-manifest.yml'
    artifactName: 'manifests'
    publishLocation: 'Container'
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: 'version'
    artifactName: 'manifests'
    publishLocation: 'Container'